// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/example-inc/zuul-operator/pkg/apis/cache/v1alpha1.Zuul":       schema_pkg_apis_cache_v1alpha1_Zuul(ref),
		"github.com/example-inc/zuul-operator/pkg/apis/cache/v1alpha1.ZuulSpec":   schema_pkg_apis_cache_v1alpha1_ZuulSpec(ref),
		"github.com/example-inc/zuul-operator/pkg/apis/cache/v1alpha1.ZuulStatus": schema_pkg_apis_cache_v1alpha1_ZuulStatus(ref),
	}
}

func schema_pkg_apis_cache_v1alpha1_Zuul(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Zuul is the Schema for the zuuls API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/example-inc/zuul-operator/pkg/apis/cache/v1alpha1.ZuulSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/example-inc/zuul-operator/pkg/apis/cache/v1alpha1.ZuulStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/example-inc/zuul-operator/pkg/apis/cache/v1alpha1.ZuulSpec", "github.com/example-inc/zuul-operator/pkg/apis/cache/v1alpha1.ZuulStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cache_v1alpha1_ZuulSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ZuulSpec defines the desired state of Zuul",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_cache_v1alpha1_ZuulStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ZuulStatus defines the observed state of Zuul",
				Type:        []string{"object"},
			},
		},
	}
}
